[project]
name = "hattrick-fun-with-flags"
version = "0.1.2"
description = "Add your description here"
authors = [
    { name = "joe", email = "github@schicker.guru" }
]
dependencies = [
    "hattrick-libs==0.9.13",
    "flask>=3.0.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
        packages = ["fun_with_flags"]

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
