name: ci

on:
  push:
    branches:
      - 'main'


jobs:
  publish-couchdb-container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to APPUiO registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REGISTRY_URL }}/${{ vars.OPENSHIFT_PROJECT }}/couchdb-image:latest
          file: docker/Dockerfile.couchdb
          build-args: |
              pw=${{ secrets.COUCHDB_PW }}


  publish-app-container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to APPUiO registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REGISTRY_URL }}/${{ vars.OPENSHIFT_PROJECT }}/fun-with-flags_app-image:latest
          file: docker/Dockerfile.app
          build-args: |
              ck=${{ secrets.HATTRICK_OAUTH_CONSUMER_KEY }}
              cs=${{ secrets.HATTRICK_OAUTH_CONSUMER_SECRET }}
              fls=${{ secrets.FLASK_SECRET }}
              fes=${{ secrets.FERNET_SECRET }}
              cdbcs=${{ secrets.COUCHDB_CONNECTION_STRING }}
              stest=${{ secrets.STRIPE_ENDPOINT_SECRET_TEST }}
              stwhst=${{ secrets.STRIPE_WEBHOOK_SECRET_TEST }}
              stes=${{ secrets.STRIPE_ENDPOINT_SECRET }}
              stwhs=${{ secrets.STRIPE_WEBHOOK_SECRET }}
              stpi=${{ secrets.STRIPE_PRICE_ITEM }}