name: ci

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: 'docker'


jobs:
  couchdb:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitLab
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull the latest github commit
        uses: actions/checkout@v3

      - name: Build the latest Docker image
        run: docker build --file Dockerfile.couchdb --tag ${{ vars.REGISTRY_URL }}/${{ vars.OPENSHIFT_PROJECT }}/couchdb-image:latest --build-arg pw=${{ secrets.COUCHDB_PW }} .

      - name: Push the latest Docker image to APPUiO Cloud
        run: docker push ${{ vars.REGISTRY_URL }}/${{ vars.OPENSHIFT_PROJECT }}/couchdb-image:latest


  app:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitLab
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull the latest github commit
        uses: actions/checkout@v3

      - name: Build the latest Docker image
        run: docker build --file Dockerfile.app --tag ${{ vars.REGISTRY_URL }}/${{ vars.OPENSHIFT_PROJECT }}/fun-with-flags_app-image:latest
                                                                                                                    --build-arg ck=${{ secrets.HATTRICK_OAUTH_CONSUMER_KEY }}
                                                                                                                    --build-arg cs=${{ secrets.HATTRICK_OAUTH_CONSUMER_SECRET }}
                                                                                                                    --build-arg fls=${{ secrets.FLASK_SECRET }}
                                                                                                                    --build-arg fes=${{ secrets.FERNET_SECRET }}
                                                                                                                    --build-arg cdbcs=${{ secrets.COUCHDB_CONNECTION_STRING }} .

      - name: Push the latest Docker image to APPUiO Cloud
        run: docker push ${{ vars.REGISTRY_URL }}/${{ vars.OPENSHIFT_PROJECT }}/fun-with-flags_app-image:latest
