name: couch-ci

on:
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: 'docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to APPUiO Cloud Registry
      run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login --password-stdin ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USERNAME }}

    - name: Build the latest Docker image
      run: docker build . --file Dockerfile.couchdb --tag ${{ secrets.REGISTRY_URL }}/${{ secrets.OPENSHIFT_PROJECT }}/couchdb-image:latest --build-arg pw=${{ secrets.COUCHDB_PW }}

    - name: Push the latest Docker image to APPUiO Cloud
      run: docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.OPENSHIFT_PROJECT }}/couchdb-image:latest


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Login to APPUiO Cloud Project
  #     run: oc login --token=${{ secrets.REGISTRY_PASSWORD }} --server=${{ secrets.OPENSHIFT_URL }}
  #   - name: Select project
  #     run: oc project ${{ secrets.OPENSHIFT_PROJECT }}
  #   - name: Deploy application
  #     run: oc apply --overwrite --filename deployment.yaml
  #   - name: Rollout latest version
  #     run: oc rollout latest dc/couchdb-image